### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by sushiljain1989** [openmul/openmul#22]
I'm trying to build the stable version of it and it's not working for me. I am a newbie.
Could anyone help me resolving the error (Check out the screenshot)

![openmul - c1](https://cloud.githubusercontent.com/assets/4305242/19683494/ae23828a-9ab2-11e6-8c96-9a552ae92509.png)

**Comment by dipjyoti** [comment]
For  glib issues, kindly check http://askubuntu.com/questions/58664/cant-install-package-libglib2-0-dev-because-it-depends-on-some-unknown-version. Once glib issue is resolved, do the following :+1: 
$  CFLAGS=`pkg-config --cflags glib-2.0` ./configure --with-vty=yes
$ make

**Comment by sushiljain1989** [comment]
@dipjyoti thanks for your answer. I am using ubuntu 14.04 and mentioned URL in your answer is not working out for me. Check out the screenshot. If you know any other way, then please help me with that. 
I tried with `aptitude` as well and the result was following :
`sudo aptitude install libglib2.0-dev
The following NEW packages will be installed:
  gcc-4.9-base:i386{ab} libc6:i386{ab} libelfg0:i386{a} libffi6:i386{ab} libgcc1:i386{ab} libglib2.0-0:i386{ab} libglib2.0-bin:i386{ab} 
  libglib2.0-dev{b} libpcre3:i386{ab} libpcre3-dev{ab} libpcrecpp0{a} libselinux1:i386{ab} zlib1g:i386{a} 
0 packages upgraded, 13 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,025 kB of archives. After unpacking 27.9 MB will be used.
The following packages have unmet dependencies:
 libselinux1 : Breaks: libselinux1:i386 (!= 2.2.2-1ubuntu0.1) but 2.2.2-1 is to be installed.
 libselinux1:i386 : Breaks: libselinux1 (!= 2.2.2-1) but 2.2.2-1ubuntu0.1 is installed.
 libgcc1 : Breaks: libgcc1:i386 (!= 1:4.9.3-0ubuntu4) but 1:4.9-20140406-0ubuntu1 is to be installed.
 libgcc1:i386 : Breaks: libgcc1 (!= 1:4.9-20140406-0ubuntu1) but 1:4.9.3-0ubuntu4 is installed.
 libc6 : Breaks: libc6:i386 (!= 2.19-0ubuntu6.9) but 2.19-0ubuntu6 is to be installed.
 libc6:i386 : Breaks: libc6 (!= 2.19-0ubuntu6) but 2.19-0ubuntu6.9 is installed.
 libglib2.0-0 : Breaks: libglib2.0-0:i386 (!= 2.40.2-0ubuntu1) but 2.40.0-2 is to be installed.
 libglib2.0-0:i386 : Breaks: libglib2.0-0 (!= 2.40.0-2) but 2.40.2-0ubuntu1 is installed.
 libglib2.0-dev : Depends: libglib2.0-0 (= 2.40.0-2) but 2.40.2-0ubuntu1 is installed.
 libpcre3-dev : Depends: libpcre3 (= 1:8.31-2ubuntu2) but 1:8.31-2ubuntu2.3 is installed.
 libglib2.0-bin : Conflicts: libglib2.0-bin:i386 but 2.40.0-2 is to be installed.
 libglib2.0-bin:i386 : Conflicts: libglib2.0-bin but 2.40.2-0ubuntu1 is installed.
 libpcre3 : Breaks: libpcre3:i386 (!= 1:8.31-2ubuntu2.3) but 1:8.31-2ubuntu2 is to be installed.
 libpcre3:i386 : Breaks: libpcre3 (!= 1:8.31-2ubuntu2) but 1:8.31-2ubuntu2.3 is installed.
 gcc-4.9-base : Breaks: gcc-4.9-base:i386 (!= 4.9.3-0ubuntu4) but 4.9-20140406-0ubuntu1 is to be installed.
 gcc-4.9-base:i386 : Breaks: gcc-4.9-base (!= 4.9-20140406-0ubuntu1) but 4.9.3-0ubuntu4 is installed.
 libffi6 : Breaks: libffi6:i386 (!= 3.1~rc1+r3.0.13-12ubuntu0.1) but 3.1~rc1+r3.0.13-12 is to be installed.
 libffi6:i386 : Breaks: libffi6 (!= 3.1~rc1+r3.0.13-12) but 3.1~rc1+r3.0.13-12ubuntu0.1 is installed.
The following actions will resolve these dependencies:

      Keep the following packages at their current version:
1)      gcc-4.9-base:i386 [Not Installed]                  
2)      libc6:i386 [Not Installed]                         
3)      libelfg0:i386 [Not Installed]                      
4)      libffi6:i386 [Not Installed]                       
5)      libgcc1:i386 [Not Installed]                       
6)      libglib2.0-0:i386 [Not Installed]                  
7)      libglib2.0-bin:i386 [Not Installed]                
8)      libglib2.0-dev [Not Installed]                     
9)      libpcre3:i386 [Not Installed]                      
10)     libpcre3-dev [Not Installed]                       
11)     libselinux1:i386 [Not Installed]                   
12)     zlib1g:i386 [Not Installed]                        



Accept this solution? [Y/n/q/?] y
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.`

~Sushil

![openmul1](https://cloud.githubusercontent.com/assets/4305242/19756029/2a698d04-9c1a-11e6-976a-0f3060e45268.png)

**Comment by dipjyoti** [comment]
It seems to me you already have glib 2.4.0 installed. I would suggest that you first remove 2.4.0 and try installing it

**Comment by dipjyoti** [comment]
It seems that  glib 2.40.2 is already installed in the system. Request to try removing it first.

**Comment by sushiljain1989** [comment]
@dipjyoti, thanks for you reply. I tried to install it in a fresh ubuntu14.04 environment, where I installed glib2.0, and it worked for me.
