### ISSUE TITLE
www.openmul.org not reachable

### ISSUE THREAD

**Issue by will-code-for-pizza** [openmul/openmul#24]
Is this project dead ?  :-(

```
ICAP Error (icap_error)
--
An error occurred while performing an ICAP operation: Server unavailable: No ICAP server is available to process request.
There could be a network problem, the ICAP service may be misconfigured, or the ICAP server may have reported an error.
For assistance, contact your network support team.
```

**Comment by dipjyoti** [comment]
This project is not yet dead. www.openmul.org is actice as well (might be
temporary downtime) .There has been much dev. activity in private branches
which are being readied for a release.

**Comment by twominutesalad** [comment]
@dipjyoti still progressing to release? I'm interested in helping contribute :-)

**Comment by dipjyoti** [comment]
Please free to contribute....
