### ISSUE TITLE
Two small bugs

### ISSUE THREAD

**Issue by 314942468GitHub** [openmul/openmul#7]
I have found two small bugs in this lastest version, both of which are in mul_nbapi_wrap.c  file‍.
(1)   line 78899:result = (uint32_t) ((arg1)->ofp_version)‍‍
(2)   line 78921:‍ result = (uint32_t) ((arg1)->ofp_version)
Each of arg1  is a  "struct mul_switch" structure,which is defined in mul_app_infra.h file.This structure has a domain of "ofp_ver" to indicate the openflow version,it is not "ofp_version" as above.‍‍‍

**Comment by openmul** [comment]
This should be resolved in the new concave release.
